### ISSUE TITLE
Negative scores are stored out of order (after positive scores)

### ISSUE THREAD

**Issue by hltbra** [Yipit/dredis#34]
This is because of their binary representation.

https://github.com/siddontang/ledisdb is the only project I've found that addresses this properly. They use a prefix indicating if the score is positive or negative, and store scores as `uint64` (negative scores overflow and start from 0). This way you have `-3` coming before `-2` because of the size overflow, but still need the prefix to not mix them with the positive numbers.

DRedis uses double precision and can't use uint64, but I think it's doable to use the same logic of maximum value and overflow.

This is dredis 1.1.0:
```
127.0.0.1:6377> zadd z -2 first -3 second 0 fourth 1 fifth 2 sixth
(integer) 5
127.0.0.1:6377> zrange z 0 -1 withscores
 1) "fourth"
 2) "0"
 3) "fifth"
 4) "1"
 5) "sixth"
 6) "2"
 7) "first"
 8) "-2"
 9) "second"
10) "-3"
```

This is Redis 3.2.6:
```
127.0.0.1:6379> zadd z -2 first -3 second 0 fourth 1 fifth 2 sixth
127.0.0.1:6379> zrange z 0 -1 withscores
 1) "second"
 2) "-3"
 3) "first"
 4) "-2"
 5) "fourth"
 6) "0"
 7) "fifth"
 8) "1"
 9) "sixth"
10) "2"
```

**Comment by hltbra** [comment]
Fixed by https://github.com/Yipit/dredis/pull/35

**Comment by andrewgross** [comment]
👀 Don't quite understand what was going on here, and would love to know more.
